In [2]:
# Import Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [4]:
# Import patient survey data into pandas from CSV
mortality_raw_df = pd.read_csv('Mortality_2016.csv')
mortality_raw_df.head()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 31, saw 3

In [18]:
mortality_raw_df[["County", "State"]] = mortality_raw_df['County'].str.split(',', expand=True)
del mortality_raw_df['County Code']
mortality_raw_df.head()

,County,Deaths,Population,Crude Rate,Crude Rate Lower 95% Confidence Interval,Crude Rate Upper 95% Confidence Interval,Crude Rate Standard Error,Age Adjusted Rate,Age Adjusted Rate Lower 95% Confidence Interval,Age Adjusted Rate Upper 95% Confidence Interval,Age Adjusted Rate Standard Error,% of Total Deaths,State
0,Autauga County,520,55416,938.36,857.7,1019.01,41.15,884.39,807.04,961.73,39.46,0.02%,AL
1,Baldwin County,1974,208563,946.48,904.72,988.23,21.3,716.92,684.42,749.41,16.58,0.07%,AL
2,Barbour County,256,25965,985.94,865.16,1106.72,61.62,800.68,700.55,900.8,51.08,0.01%,AL
3,Bibb County,239,22643,1055.51,921.69,1189.33,68.28,927.67,808.06,1047.28,61.03,0.01%,AL
4,Blount County,697,57704,1207.89,1118.21,1297.56,45.75,989.37,914.2,1064.54,38.35,0.03%,AL

In [19]:
clean_mortality = mortality_df[["State", "County", "Deaths", "Population", "Crude Rate",
                           "Age Adjusted Rate", "% of Total Deaths"]]
clean_mortality.head()

,State,County,Deaths,Population,Crude Rate,Age Adjusted Rate,% of Total Deaths
0,AL,Autauga County,520,55416,938.36,884.39,0.02%
1,AL,Baldwin County,1974,208563,946.48,716.92,0.07%
2,AL,Barbour County,256,25965,985.94,800.68,0.01%
3,AL,Bibb County,239,22643,1055.51,927.67,0.01%
4,AL,Blount County,697,57704,1207.89,989.37,0.03%

In [20]:
clean_mortality["County"] = clean_mortality["County"].str.replace("County", "")
clean_mortality.head()

C:\Users\Vilma\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

,State,County,Deaths,Population,Crude Rate,Age Adjusted Rate,% of Total Deaths
0,AL,Autauga,520,55416,938.36,884.39,0.02%
1,AL,Baldwin,1974,208563,946.48,716.92,0.07%
2,AL,Barbour,256,25965,985.94,800.68,0.01%
3,AL,Bibb,239,22643,1055.51,927.67,0.01%
4,AL,Blount,697,57704,1207.89,989.37,0.03%

In [21]:
clean_mortality["County"] = clean_mortality["County"].str.upper()
clean_mortality.head()

C:\Users\Vilma\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

,State,County,Deaths,Population,Crude Rate,Age Adjusted Rate,% of Total Deaths
0,AL,AUTAUGA,520,55416,938.36,884.39,0.02%
1,AL,BALDWIN,1974,208563,946.48,716.92,0.07%
2,AL,BARBOUR,256,25965,985.94,800.68,0.01%
3,AL,BIBB,239,22643,1055.51,927.67,0.01%
4,AL,BLOUNT,697,57704,1207.89,989.37,0.03%

In [1]:
# make new df
mortality_df = pd.DataFrame(clean_mortality)

mortality_df.head()

NameError: name 'pd' is not defined

In [23]:
# Save as csv
clean_mortality.to_csv("mortality_2016_final.csv")