# RESOURCES

HCAPS hospital survey: https://data.medicare.gov/Hospital-Compare/Patient-survey-HCAHPS-Hospital/dgck-syfz

population data: https://www.census.gov/data/tables/2016/demo/popest/total-cities-and-towns.html#par_textimage

CDC API info: https://wonder.cdc.gov/wonder/help/WONDER-API.html

In [4]:
# Import Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import collections

In [5]:
# Import patient survey data into pandas from CSV
survey_raw_df = pd.read_csv('Resources/Patient_survey__HCAHPS__-_Hospital.csv')

print(f'Total number of unique hospitals: {survey_raw_df["Hospital Name"].nunique()}')
survey_raw_df.head()

Total number of unique hospitals: 4613

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,HCAHPS Measure ID,HCAHPS Question,...,HCAHPS Answer Percent,HCAHPS Answer Percent Footnote,HCAHPS Linear Mean Value,Number of Completed Surveys,Number of Completed Surveys Footnote,Survey Response Rate Percent,Survey Response Rate Percent Footnote,Measure Start Date,Measure End Date,Location
0,240018,MAYO CLINIC HEALTH SYSTEM - RED WING,"701 HEWITT BOULEVARD, PO BOX 95",RED WING,MN,55066,GOODHUE,6512675000,H_COMP_3_LINEAR_SCORE,Staff responsiveness - linear mean score,...,Not Applicable,NaN,93,347,NaN,33,NaN,07/01/2016,06/30/2017,"701 HEWITT BOULEVARD, PO BOX 95\nRED WING, MN\..."
1,231334,PROMEDICA HERRICK HOSPITAL,500 E POTTAWATAMIE STREET,TECUMSEH,MI,49286,LENAWEE,5174243000,H_QUIET_HSP_SN_P,Patients who reported that the area around the...,...,Not Available,1 - The number of cases/patients is too few to...,Not Applicable,Not Available,1 - The number of cases/patients is too few to...,Not Available,1 - The number of cases/patients is too few to...,07/01/2016,06/30/2017,"500 E POTTAWATAMIE STREET\nTECUMSEH, MI\n(42.0..."
2,231332,BRONSON LAKEVIEW HOSPITAL,408 HAZEN STREET,PAW PAW,MI,49079,VAN BUREN,2696571400,H_COMP_1_A_P,"Patients who reported that their nurses ""Alway...",...,85,11 - There were discrepancies in the data coll...,Not Applicable,130,11 - There were discrepancies in the data coll...,30,11 - There were discrepancies in the data coll...,07/01/2016,06/30/2017,"408 HAZEN STREET\nPAW PAW, MI\n(42.221009, -85..."
3,240010,MAYO CLINIC HOSPITAL ROCHESTER,1216 SECOND STREET SOUTHWEST,ROCHESTER,MN,55902,OLMSTED,5072555123,H_RECMND_PY,"Patients who reported YES, they would probably...",...,15,NaN,Not Applicable,708,NaN,38,NaN,07/01/2016,06/30/2017,"1216 SECOND STREET SOUTHWEST\nROCHESTER, MN\n(..."
4,231330,MARLETTE REGIONAL HOSPITAL,2770 MAIN STREET,MARLETTE,MI,48453,SANILAC,9896354000,H_COMP_5_LINEAR_SCORE,Communication about medicines - linear mean score,...,Not Applicable,NaN,76,119,NaN,38,NaN,07/01/2016,06/30/2017,"2770 MAIN STREET\nMARLETTE, MI\n(43.332579, -8..."

In [6]:
# Only include survey columns with "State", "City", "Hospital Name", 
# "Patient Survey Star Rating", "Number of Completed Surveys", "Survey Response Rate Percent", "Location"
# create ordered dict to hold values
hospital_dict = collections.OrderedDict([("State", []),
                                    ("County", []),
                                    ("City", []),
                                    ("Hospital", []),
                                    ("Location", []),
                                    ("Patient Rating", []),
                                    ("Completed Surveys", []),
                                    ("Survey Response Rate (%)", [])])


# Only include survey rows with hospital "HCAHPS Measure ID" == "H_STAR_RATING"
for index, hospital in survey_raw_df.iterrows():
    if (hospital["HCAHPS Measure ID"] == "H_STAR_RATING") and (hospital["Patient Survey Star Rating"] != "Not Available"):
        hospital_dict["State"].append(hospital["State"])
        hospital_dict["County"].append(hospital["County Name"])
        hospital_dict["City"].append(hospital["City"])
        hospital_dict["Hospital"].append(hospital["Hospital Name"])
        hospital_dict["Location"].append(hospital["Location"])
        hospital_dict["Patient Rating"].append(hospital["Patient Survey Star Rating"])
        hospital_dict["Completed Surveys"].append(hospital["Number of Completed Surveys"])
        hospital_dict["Survey Response Rate (%)"].append(hospital["Survey Response Rate Percent"])

# make dataframe                      
hospital_df = pd.DataFrame(hospital_dict)

# print dataframe
hospital_df.head()

,State,County,City,Hospital,Location,Patient Rating,Completed Surveys,Survey Response Rate (%)
0,MN,HENNEPIN,ROBBINSDALE,NORTH MEMORIAL MEDICAL CENTER,"3300 OAKDALE NORTH\nROBBINSDALE, MN\n(45.01421...",3,957,26
1,AL,MARSHALL,BOAZ,MARSHALL MEDICAL CENTER SOUTH,"2505 U S HIGHWAY 431 NORTH\nBOAZ, AL\n",3,1250,35
2,MN,OLMSTED,ROCHESTER,MAYO CLINIC HOSPITAL ROCHESTER,"1216 SECOND STREET SOUTHWEST\nROCHESTER, MN\n(...",4,708,38
3,MN,GOODHUE,RED WING,MAYO CLINIC HEALTH SYSTEM - RED WING,"701 HEWITT BOULEVARD, PO BOX 95\nRED WING, MN\...",4,347,33
4,MN,SAINT LOUIS,DULUTH,ESSENTIA HEALTH ST MARY'S MEDICAL CENTER,"407 EAST THIRD STREET\nDULUTH, MN\n(46.792843,...",3,1816,31

In [7]:
print(f"Total # of hospitals with star ratings: {data_df.Hospital.count()}")

# export df to csv
hospital_df.to_csv('Resources/hospital_cleaned_data.csv')

Total # of hospitals with star ratings: 3470

In [8]:
# Import mortality data (with population data)
mortality_df = pd.read_csv('Resources/mortality_2016_final.csv')

mortality_df.head()

,Unnamed: 0,State,County,Deaths,Population,Crude Rate,Age Adjusted Rate,% of Total Deaths
0,0,AL,AUTAUGA,520,55416,938.36,884.39,0.02%
1,1,AL,BALDWIN,1974,208563,946.48,716.92,0.07%
2,2,AL,BARBOUR,256,25965,985.94,800.68,0.01%
3,3,AL,BIBB,239,22643,1055.51,927.67,0.01%
4,4,AL,BLOUNT,697,57704,1207.89,989.37,0.03%

In [16]:
# merge df on state and county
data_df = pd.merge(hospital_df, mortality_df, how="outer", on=["State", "County"])

# may have to change type to int (astype(int)) before merging
# remove percent in deaths
# remove unnamed column

data_df.head()

,State,County,City,Hospital,Location,Patient Rating,Completed Surveys,Survey Response Rate (%),Unnamed: 0,Deaths,Population,Crude Rate,Age Adjusted Rate,% of Total Deaths
0,MN,HENNEPIN,ROBBINSDALE,NORTH MEMORIAL MEDICAL CENTER,"3300 OAKDALE NORTH\nROBBINSDALE, MN\n(45.01421...",3,957,26,NaN,NaN,NaN,NaN,NaN,NaN
1,MN,HENNEPIN,MINNEAPOLIS,HENNEPIN COUNTY MEDICAL CENTER 1,"701 PARK AVENUE\nMINNEAPOLIS, MN\n(44.97285, -...",2,694,13,NaN,NaN,NaN,NaN,NaN,NaN
2,MN,HENNEPIN,SAINT LOUIS PARK,PARK NICOLLET METHODIST HOSPITAL,"6500 EXCELSIOR BLVD\nSAINT LOUIS PARK, MN\n(44...",3,1199,34,NaN,NaN,NaN,NaN,NaN,NaN
3,MN,HENNEPIN,MINNEAPOLIS,ABBOTT NORTHWESTERN HOSPITAL,"800 EAST 28TH STREET\nMINNEAPOLIS, MN\n(44.951...",3,865,35,NaN,NaN,NaN,NaN,NaN,NaN
4,MN,HENNEPIN,MINNEAPOLIS,"UNIVERSITY OF MINNESOTA MEDICAL CENTER, FAIRVIEW","2450 RIVERSIDE AVENUE\nMINNEAPOLIS, MN\n(44.96...",3,515,25,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#visualize relationships between county mortality rates, hospital count, hospital star rating, 
# hospitals per capita, using matplotlib (opt. seaborn, tableau plot on map)